### ISSUE TITLE
sql query not work when i used spark3.0-preview2 

### ISSUE THREAD

**Issue by zachary124** [apache/incubator-iceberg#1010]

**Comment by zachary124** [comment]
hello，I want to use sparkSQL query iceberg hive table just like I query other hive table。I had build iceberg branch spark-3 and can create table and query table use spark。 but when I query the hive table use sql， it returned an error :
`java.lang.RuntimeException: java.lang.InstantiationException
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:134)
	at org.apache.spark.rdd.HadoopRDD.getInputFormat(HadoopRDD.scala:191)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:205)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:276)
	at scala.Option.getOrElse(Option.scala:138)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:272)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:276)
	at scala.Option.getOrElse(Option.scala:138)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:272)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:276)
	at scala.Option.getOrElse(Option.scala:138)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:272)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:276)
	at scala.Option.getOrElse(Option.scala:138)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:272)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:276)
	at scala.Option.getOrElse(Option.scala:138)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:272)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:408)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:47)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3482)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2581)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3472)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$4(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:87)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3468)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2581)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2788)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:297)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:334)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:818)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:795)
	at com.zachary.lake.SparkIcebergTestJob.createByHive(SparkIcebergTestJob.java:66)`

my code is 
![image](https://user-images.githubusercontent.com/3360971/81281138-06ac5580-908c-11ea-9abd-537e28dc278d.png)

thanks

**Comment by zachary124** [comment]
I tried it on spark2.4.4, and the problem was the same, so I switched to spark3 and tried again

**Comment by rdblue** [comment]
Looks like you're trying to load an Iceberg table without going through an Iceberg catalog. Iceberg stores table references in the Hive metastore, but non-Iceberg catalogs cannot read the tables.

In Spark 2.4.4, you need to use the Dataset API and register your table as a temporary view to use SQL. That's documented on our [Getting Started page](https://iceberg.apache.org/getting-started/#reading-with-sql).

In Spark 3.0, you need to use the 3.0 branch and register an Iceberg catalog with Spark. That's done by setting config properties that point to the [SparkCatalog](https://github.com/apache/incubator-iceberg/blob/spark-3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java) implementation:

```
spark.sql.catalog.iceberg = org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.uri = thrift://... # your HMS connection URI
```

Once you've defined that catalog, you can use it in SQL:

```sql
SELECT * FROM iceberg.ice.data4
```

**Comment by zachary124** [comment]
@rdblue Thank you for your reply，I get it
