### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by HelloHorizon** [apache/incubator-iceberg#245]
While creating Iceberg table using PartitionSpec.builderFor, I faced the `java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V` error.

I use the Iceberg-master and Spark 2.4.0.

```
import org.apache.hadoop.fs.Path
import org.apache.iceberg.hadoop.HadoopTables
import org.apache.iceberg.spark.SparkSchemaUtil
import org.apache.iceberg.PartitionSpec


val path = "hdfs://${TABLE_PATH}"
val df = spark.read.parquet("/user/hive/warehouse/tpcds.db/web_sales")

{
    val conf = spark.sparkContext.hadoopConfiguration
    val fs = new Path(path).getFileSystem(conf)
    fs.delete(new Path(path), true)
    val tables = new HadoopTables(conf)
    val icebergSchema = SparkSchemaUtil.convert(df.schema)
    val spec = PartitionSpec.builderFor(icebergSchema)
    .identity("ws_sold_date_sk")
    .identity("ws_sold_time_sk")
    .identity("ws_ship_date_sk")
    .identity("ws_item_sk")
    .identity("ws_bill_customer_sk")
    .identity("ws_bill_cdemo_sk")
    .identity("ws_bill_hdemo_sk")
    .identity("ws_bill_addr_sk")
    .identity("ws_ship_customer_sk")
    .identity("ws_ship_cdemo_sk")
    .identity("ws_ship_hdemo_sk")
    .identity("ws_ship_addr_sk")
    .identity("ws_web_page_sk")
    .identity("ws_web_site_sk")
    .identity("ws_ship_mode_sk")
    .identity("ws_warehouse_sk")
    .identity("ws_promo_sk")
    .identity("ws_order_number")
    .identity("ws_quantity")
    .identity("ws_wholesale_cost")
    .identity("ws_list_price")
    .identity("ws_sales_price")
    .identity("ws_ext_discount_amt")
    .identity("ws_ext_sales_price")
    .identity("ws_ext_wholesale_cost")
    .identity("ws_ext_list_price")
    .identity("ws_ext_tax")
    .identity("ws_coupon_amt")
    .identity("ws_ext_ship_cost")
    .identity("ws_net_paid")
    .identity("ws_net_paid_inc_tax")
    .identity("ws_net_paid_inc_ship")
    .identity("ws_net_paid_inc_ship_tax")
    .identity("ws_net_profit")
    .build()
    tables.create(icebergSchema, spec, path)
    tables.load(path).schema
}
```

```
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
  at org.apache.iceberg.PartitionSpec$Builder.checkAndAddPartitionName(PartitionSpec.java:330)
  at org.apache.iceberg.PartitionSpec$Builder.identity(PartitionSpec.java:356)
  ... 93 elided
```

I appreciate if anyone can help me with this problem.

**Comment by HelloHorizon** [comment]
Solved by adding relocate 'com.google.common', 'com.google.common.version28' in build.gradle.

**Comment by chris-alphonso** [comment]
@HelloHorizon Where did you add this and were there any other steps? I'm facing the same issue. Thanks

**Comment by HelloHorizon** [comment]
@chris-alphonso For me, it is because of Guava version conflict. Since Spark v2.4.0 use 14.0.1 while iceberg use 28.0, you only need to add relocation for shardowjar in `build.gradle`. Add `relocate 'com.google.common', 'com.google.common.version28'` at line 415.

**Comment by Voltir** [comment]
We ran into this issue as well, should the workaround land on master?

**Comment by Voltir** [comment]
@rdblue I know this issue appears to be closed, but I noticed that we run into this problem when trying to use the iceberg artifact published on maven with spark 2.4.4. Is there a downside to "relocating" google commons in iceberg?

**Comment by rdblue** [comment]
@Voltir, that sounds fine to me. I don't think I saw this issue when it was open so I didn't realize there was a conflict. Would you like to open a PR to relocate Guava?

**Comment by Voltir** [comment]
@rdblue Sure, I will open a PR shortly.
