### ISSUE TITLE
iceberg-spark-runtime should not shade Hive classes it does not include in its shaded jar

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#260]
I see the following exception when using spark-runtime jar. 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/iceberg/shaded/org/apache/hadoop/hive/metastore/api/NoSuchObjectException
	at HiveTables$.<init>(HiveTables.scala:9)
	at HiveTables$.<clinit>(HiveTables.scala)
	at HiveTables.main(HiveTables.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.iceberg.shaded.org.apache.hadoop.hive.metastore.api.NoSuchObjectException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

```

It seems that we are shading Metastore classes even though we are not bundling them in the shaded jar. 

I have a patch working for this which I'll post later in the day.

**Comment by rdblue** [comment]
Thanks for working on this!

**Comment by sarangshinde** [comment]
Getting same error in 0.8.0(latest as of today) version as well.
