### ISSUE TITLE
supports unpartitioned table in partitionDF

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#415]
partitionDF throws exception when executing on unpartitioned table, please see following exception:
```
org.apache.hadoop.hive.ql.metadata.HiveException: Table item is not a partitioned table
  at org.apache.hadoop.hive.ql.metadata.Hive.getPartitions(Hive.java:2123)
  at org.apache.hadoop.hive.ql.metadata.Hive.getPartitions(Hive.java:2156)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getPartitions$1.apply(HiveClientImpl.scala:670)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getPartitions$1.apply(HiveClientImpl.scala:662)
  at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$withHiveState$1.apply(HiveClientImpl.scala:275)
  at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:213)
  at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:212)
  at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:258)
  at org.apache.spark.sql.hive.client.HiveClientImpl.getPartitions(HiveClientImpl.scala:662)
  at org.apache.spark.sql.hive.client.HiveClient$class.getPartitions(HiveClient.scala:210)
  at org.apache.spark.sql.hive.client.HiveClientImpl.getPartitions(HiveClientImpl.scala:83)
  at org.apache.iceberg.spark.hacks.Hive.partitions(Hive.java:48)
  at org.apache.iceberg.spark.SparkTableUtil$.partitionDF(SparkTableUtil.scala:56)
```

**Comment by chenjunjiedada** [comment]
Close this first, will add some doc to `partitionDF` to address it.
