### ISSUE TITLE
TIME_MICROS not supported for reading (Parquet)

### ISSUE THREAD

**Issue by ashleycoxley** [apache/incubator-iceberg#482]
In attempting to read some `TIME_MICROS` (Iceberg `TIME` type) data with `GenericParquetReaders`, I'm running into the following error message. I wonder if this is intended, or an oversight in handling read types:

```
Unsupported logical type: TIME_MICROS
java.lang.UnsupportedOperationException: 
	at com.netflix.iceberg.data.parquet.GenericParquetReaders$ReadBuilder.primitive(GenericParquetReaders.java:249)
	at com.netflix.iceberg.data.parquet.GenericParquetReaders$ReadBuilder.primitive(GenericParquetReaders.java:112)
	at com.netflix.iceberg.parquet.TypeWithSchemaVisitor.visit(TypeWithSchemaVisitor.java:49)
	at com.netflix.iceberg.parquet.TypeWithSchemaVisitor.visitField(TypeWithSchemaVisitor.java:151)
	at com.netflix.iceberg.parquet.TypeWithSchemaVisitor.visitFields(TypeWithSchemaVisitor.java:165)
	at com.netflix.iceberg.parquet.TypeWithSchemaVisitor.visit(TypeWithSchemaVisitor.java:44)
	at com.netflix.iceberg.data.parquet.GenericParquetReaders.buildReader(GenericParquetReaders.java:72)
```

**Comment by rdblue** [comment]
Looks like something that should be supported. Would you like to open a PR to fix it?

I think this just needs to be added here: https://github.com/apache/incubator-iceberg/blob/master/data/src/main/java/org/apache/iceberg/data/parquet/GenericParquetReaders.java#L216-L231

**Comment by ashleycoxley** [comment]
Done! Thanks :)
