### ISSUE TITLE
Concurrently delete a data file

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#493]
I have a multi-threading (2 threads) Spark App to concurrently delete a data file, using 
```
table.newDelete().deleteFile("path").commit()
```
1. I am expecting a commit failure was reported but it seems no related messages issued. Should I?
2. Looking into the metadata folder, I see 2 manifests, 2 manifest list, and 2 metadata json files (with the same prefix number) generated. Expected behavior?
3. Comparing the 2 metadata json file, I found each metadata json file has a snapshot that contains the same "delete" operation, and they have the same "parent-snapshot-id". The same as that in  the "snapshot-log" section. I think the "delete" operation is eventually made by 1 commit, is it supposed to be only included in one of the snapshot, but not both. And does it break the "linear" update on snapshot chain as the pervious snapshot has 2 snapshots as its successor?

2 metadata json files attached as below:
[00002-242fcf90-f169-4e4a-b7d9-6ee19d263734.metadata.json.txt](https://github.com/apache/incubator-iceberg/files/3647251/00002-242fcf90-f169-4e4a-b7d9-6ee19d263734.metadata.json.txt)
[00002-c6f559bf-dbb1-4279-8120-e23d8aa45414.metadata.json.txt](https://github.com/apache/incubator-iceberg/files/3647252/00002-c6f559bf-dbb1-4279-8120-e23d8aa45414.metadata.json.txt)

**Comment by rdblue** [comment]
This doesn't fail because deletes are idempotent. You tell Iceberg to delete with a filter or to delete a specific file, and that data will not be in the table after the delete commits.

That's also why you see multiple delete operations. You ran 2 successful deletes on the table.

The two metadata files you posted are two attempts to delete at the same time. That's why they use the same parent snapshot ID. The metastore must guarantee an atomic swap that is used to get a linear history of changes. So only one of these deletes will have been successfully committed. The other would have had to retry.

**Comment by waterlx** [comment]
@rdblue Thanks very much for the detailed explanation!
Some follow-up questions:
1. Regarding

> The metastore must guarantee an atomic swap that is used to get a linear history of changes. So only one of these deletes will have been successfully committed.

After those 2 delete operations, I found one metadata json pasted above is "metadata_location" in metastore while the other metadata json is "previous_metadata_location". Does that indicate that each of them was committed successfully as "current" metadata location in metastore sometime?

2. Regarding
> The other would have had to retry.

Any message indicate a retry happens? Should I expect "WARN Retrying task after failure..." here?

3. I see the following warn about "retry" when I was trying to concurrently append data by DataFrameWriter
```
19/09/23 16:02:31 WARN Tasks: Retrying task after failure: metadataLocation = file:///Users/seanxiangli/Documents/ws/spark-warehouse/default.db/lxtest/metadata/00000-cb114a56-f37c-4824-abcb-3d510e8b0138.metadata.json is not same as table metadataLocation file:///Users/seanxiangli/Documents/ws/spark-warehouse/default.db/lxtest/metadata/00001-ea4bb37b-e664-4d13-a474-44dd17997179.metadata.json for default.lxtest
org.apache.iceberg.exceptions.CommitFailedException: metadataLocation = file:///Users/seanxiangli/Documents/ws/spark-warehouse/default.db/lxtest/metadata/00000-cb114a56-f37c-4824-abcb-3d510e8b0138.metadata.json is not same as table metadataLocation file:///Users/seanxiangli/Documents/ws/spark-warehouse/default.db/lxtest/metadata/00001-ea4bb37b-e664-4d13-a474-44dd17997179.metadata.json for default.lxtest
	at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:158)
	at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:102)
	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:249)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:403)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:212)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:188)
	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:237)
	at org.apache.iceberg.spark.source.Writer.commitOperation(Writer.java:148)
	at org.apache.iceberg.spark.source.Writer.append(Writer.java:162)
	at org.apache.iceberg.spark.source.Writer.commit(Writer.java:130)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:76)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:260)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at ThreadExample.run(Test.scala:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Does it indicate that all updates are committing and updating the metadata in line(one after another)? Why does that happen when concurrent append but not concurrent delete?

**Comment by rdblue** [comment]
> Does that indicate that each of them was committed successfully as "current" metadata location in metastore sometime?

Yes. The metadata_location always replaces previous_metadata_location.

> Any message indicate a retry happens? Should I expect "WARN Retrying task after failure..." here?

Yes, retries are logged.

> Why does that happen when concurrent append but not concurrent delete?

Commits always form a linear history. A commit may not have needed to retry, which could be why you don't see the warning. Concurrent operations are hard to predict, which is why we test concurrent changes by running lots of them in a loop. You can't guarantee a conflict.

**Comment by waterlx** [comment]
Thanks very much! I am closing this issue.
